;;; config-editing.el --- Editing state and hygiene defaults -*- lexical-binding: t; -*-

;;; Commentary:
;; This module owns the small defaults that make Emacs feel dependable during
;; everyday code work: generated files go under var/, buffers notice on-disk
;; changes, point positions are restored, long generated files do not bog down
;; redisplay, and code buffers clean trailing whitespace before save. These are
;; intentionally cross-cutting editor behaviors rather than language features.

;;; Code:

(require 'autorevert)
(require 'files)
(require 'saveplace)
(require 'so-long)

(defcustom my/editing-var-directory
  (expand-file-name "var/" user-emacs-directory)
  "Directory for local runtime files generated by editing features."
  :type 'directory
  :group 'convenience)

(defcustom my/editing-fill-column 100
  "Default fill column for buffers that do not set a language-specific value."
  :type 'integer
  :group 'convenience)

(defconst my/editing-backup-directory
  (expand-file-name "backups/" my/editing-var-directory)
  "Directory for backup files created by Emacs.")

(defconst my/editing-auto-save-directory
  (expand-file-name "auto-save/" my/editing-var-directory)
  "Directory for auto-save files created by Emacs.")

(defun my/editing-ensure-runtime-directories ()
  "Create editing runtime directories if they do not already exist."
  (dolist (directory (list my/editing-var-directory
                           my/editing-backup-directory
                           my/editing-auto-save-directory))
    (make-directory directory t)))

(defun my/editing-clean-code-whitespace-on-save ()
  "Clean trailing whitespace before saving code and config buffers."
  (add-hook 'before-save-hook #'delete-trailing-whitespace nil t))

(defun my/editing-code-buffer-visuals ()
  "Enable low-noise visual guides in programming buffers."
  (setq-local show-trailing-whitespace t)
  (when (fboundp 'display-fill-column-indicator-mode)
    (display-fill-column-indicator-mode 1)))

(my/editing-ensure-runtime-directories)

;; Keep generated safety files out of source trees. This preserves the config
;; repository's cleanliness and avoids surprising backup files in checked-out
;; work projects.
(setq backup-directory-alist `(("." . ,my/editing-backup-directory))
      auto-save-file-name-transforms
      `((".*" ,my/editing-auto-save-directory t))
      auto-save-list-file-prefix
      (expand-file-name ".saves-" my/editing-auto-save-directory))

;; These defaults are small, but they remove a lot of friction: selections are
;; replaced by typing, files refresh after external tools edit them, and point
;; returns to where the user last worked.
(setq-default fill-column my/editing-fill-column
              require-final-newline t)
(setq sentence-end-double-space nil
      kill-do-not-save-duplicates t
      auto-revert-verbose nil)

(delete-selection-mode 1)
(global-auto-revert-mode 1)
(global-so-long-mode 1)
(save-place-mode 1)
(column-number-mode 1)
(show-paren-mode 1)

(add-hook 'prog-mode-hook #'my/editing-clean-code-whitespace-on-save)
(add-hook 'conf-mode-hook #'my/editing-clean-code-whitespace-on-save)
(add-hook 'prog-mode-hook #'my/editing-code-buffer-visuals)

(provide 'config-editing)

;;; config-editing.el ends here
